/**
 * What just happened, in words.
 *
 * The current step is stated plainly at the top, with the steps before it beneath as a transcript, so
 * a user can read back over what the program did rather than having to remember it.
 *
 * Generated by template from the trace. No model, no network, no key — the trace already carries every
 * fact a sentence needs, including the source text of conditions. It is instant, works offline, and
 * says the same thing every time, which matters when someone is comparing what they see against a
 * tutorial or against what they saw a minute ago.
 */

import { useEffect, useMemo, useRef } from "react";

import type { Language } from "@flow-view/trace-schema";
import { type NarratedStep, narrateCurrent, narrateHistory } from "@flow-view/narration";
import type { TraceStore } from "@flow-view/trace-store";

import { formatValue } from "./format.js";
import { useTraceVersion } from "./useStore.js";

export interface NarrationPaneProps {
  readonly store: TraceStore;
  readonly language: Language;
  /** How many earlier steps to keep in the transcript. */
  readonly history?: number;
}

export function NarrationPane({ store, language, history = 40 }: NarrationPaneProps) {
  const version = useTraceVersion(store);
  const endRef = useRef<HTMLDivElement | null>(null);

  const options = useMemo(
    () => ({
      language,
      format: (value: Parameters<typeof formatValue>[0], state: Parameters<typeof formatValue>[1]["state"]) =>
        formatValue(value, { language, state }),
    }),
    [language],
  );

  const current = useMemo(
    () => narrateCurrent(store, options),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [store, version, options],
  );

  const earlier = useMemo(
    () => {
      const all = narrateHistory(store, { ...options, limit: history + 1 });
      // The last entry is the current step, shown separately above.
      return all.slice(0, Math.max(0, all.length - 1)).filter((entry) => entry.sentences.length > 0);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [store, version, options, history],
  );

  useEffect(() => {
    endRef.current?.scrollIntoView({ block: "nearest" });
  }, [version]);

  return (
    <div className="fv-pane fv-narration">
      <div className="fv-pane-title">
        <span>What is happening</span>
        <span className="fv-muted">step {Math.max(0, store.state.step)}</span>
      </div>

      <div className="fv-pane-body fv-narration-body">
        {earlier.length === 0 && !current ? (
          <p className="fv-empty">Step forward and this will describe what the program did.</p>
        ) : null}

        {earlier.map((entry) => (
          <Entry key={`${entry.index}`} entry={entry} onSeek={() => store.seekStep(entry.step)} />
        ))}

        {current && current.sentences.length > 0 ? (
          <Entry entry={current} emphasis />
        ) : current ? (
          <p className="fv-narration-quiet">
            About to run line {current.line ?? "?"}. Nothing has changed yet.
          </p>
        ) : null}

        <div ref={endRef} />
      </div>
    </div>
  );
}

function Entry({
  entry,
  emphasis = false,
  onSeek,
}: {
  entry: NarratedStep;
  emphasis?: boolean;
  onSeek?: () => void;
}) {
  return (
    <div className={`fv-narration-step${emphasis ? " is-current" : ""}`}>
      <button
        type="button"
        className="fv-narration-line"
        onClick={onSeek}
        disabled={!onSeek}
        title={onSeek ? "Go back to this step" : undefined}
      >
        {entry.line ?? "-"}
      </button>
      <div className="fv-narration-text">
        {entry.sentences.map((sentence, index) => (
          <p key={index} className={`fv-said is-${sentence.kind}`}>
            {renderInline(sentence.text)}
          </p>
        ))}
      </div>
    </div>
  );
}

/**
 * Render backtick spans as code.
 *
 * The templates mark variable names and expressions with backticks so that prose and code are
 * distinguishable at a glance — `values[j] > values[j + 1]` inside a sentence is much easier to read
 * as code than as words.
 */
function renderInline(text: string) {
  const parts = text.split(/(`[^`]+`)/g);
  return parts.map((part, index) =>
    part.startsWith("`") && part.endsWith("`") && part.length > 2 ? (
      <code key={index}>{part.slice(1, -1)}</code>
    ) : (
      <span key={index}>{part}</span>
    ),
  );
}
